name: Deploy Blazor to GitHub Pages

on:
  push:
    branches: [ main ]  # Cambia a 'master' si es tu rama principal
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build and Publish
      run: dotnet publish -c Release -o release --nologo
    
    - name: Debug - List files
      run: |
        echo "=== Contenido de release/ ==="
        ls -la release/
        echo "=== Buscando wwwroot ==="
        find release/ -name "wwwroot" -type d
        echo "=== Buscando index.html ==="
        find release/ -name "index.html"
    
    - name: Change base-tag in index.html
      run: sed -i 's/<base href="\/" \/>/<base href="\/BlazorApp2\/" \/>/g' release/wwwroot/index.html
    
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
    
    - name: Copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: release/wwwroot
    
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4